const newImageSrc = "https://seikoshopbucket.s3.ap-southeast-2.amazonaws.com/flieger/srph21k1.png";

const seikoWatches = [
    // Prospex
    {
      collection: "Prospex",
      model: "SPB143",
      imageSrc: newImageSrc,
      productName: "Seiko Prospex Diver SPB143",
      price: 1200,
      diameter: 40.5,
      thickness: 13.9,
      movement: "Automatic 6R35",
      waterResistance: "200m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Silicone",
      features: ["Date Display", "LumiBrite Hands and Markers"],
      color: "Gray Dial",
    },
    {
      collection: "Prospex",
      model: "SRPD21",
      imageSrc: newImageSrc,
      productName: "Seiko Prospex Turtle SRPD21",
      price: 450,
      diameter: 45,
      thickness: 13.4,
      movement: "Automatic 4R36",
      waterResistance: "200m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Rubber",
      features: ["Day-Date Display", "Rotating Bezel"],
      color: "Blue Dial",
    },
    {
      collection: "Prospex",
      model: "SLA043",
      imageSrc: newImageSrc,
      productName: "Seiko Prospex 1970 Diver's Re-creation SLA043",
      price: 4500,
      diameter: 45,
      thickness: 15.7,
      movement: "Automatic 8L35",
      waterResistance: "200m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Silicone",
      features: ["Limited Edition", "LumiBrite"],
      color: "Black Dial",
    },
    {
      collection: "Prospex",
      model: "SSC813",
      imageSrc: newImageSrc,
      productName: "Seiko Prospex Speedtimer SSC813",
      price: 675,
      diameter: 39,
      thickness: 13.3,
      movement: "Solar V192",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Chronograph", "Tachymeter"],
      color: "White Dial",
    },
    {
      collection: "Prospex",
      model: "SRPH77",
      imageSrc: newImageSrc,
      productName: "Seiko Prospex Street Series SRPH77",
      price: 550,
      diameter: 43.2,
      thickness: 12.7,
      movement: "Automatic 4R36",
      waterResistance: "200m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Silicone",
      features: ["Day-Date Display", "LumiBrite"],
      color: "Green Dial",
    },
    // Presage
    {
      collection: "Presage",
      model: "SRPB43",
      imageSrc: newImageSrc,
      productName: "Seiko Presage Cocktail Time SRPB43",
      price: 425,
      diameter: 40.5,
      thickness: 11.8,
      movement: "Automatic 4R35",
      waterResistance: "50m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Exhibition Case Back"],
      color: "Blue Dial",
    },
    {
      collection: "Presage",
      model: "SPB161",
      imageSrc: newImageSrc,
      productName: "Seiko Presage Arita Porcelain SPB161",
      price: 1700,
      diameter: 40.5,
      thickness: 12.4,
      movement: "Automatic 6R27",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Power Reserve Indicator", "Date Display"],
      color: "White Dial",
    },
    {
      collection: "Presage",
      model: "SSA409",
      imageSrc: newImageSrc,
      productName: "Seiko Presage SSA409",
      price: 525,
      diameter: 40.5,
      thickness: 14.4,
      movement: "Automatic 4R57",
      waterResistance: "50m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Power Reserve Indicator", "Open Heart"],
      color: "Green Dial",
    },
    {
      collection: "Presage",
      model: "SPB223",
      imageSrc: newImageSrc,
      productName: "Seiko Presage Sharp Edged SPB223",
      price: 1000,
      diameter: 39.3,
      thickness: 11.1,
      movement: "Automatic 6R35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Date Display", "Exhibition Case Back"],
      color: "Black Dial",
    },
    {
      collection: "Presage",
      model: "SRPE19",
      imageSrc: newImageSrc,
      productName: "Seiko Presage Enamel SRPE19",
      price: 1100,
      diameter: 40.5,
      thickness: 12.4,
      movement: "Automatic 6R35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Enamel Dial"],
      color: "White Dial",
    },
    // Astron
    {
      collection: "Astron",
      model: "SSH003",
      imageSrc: newImageSrc,
      productName: "Seiko Astron GPS Solar SSH003",
      price: 2200,
      diameter: 42.7,
      thickness: 13.3,
      movement: "GPS Solar 5X53",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Titanium",
      strapMaterial: "Titanium",
      features: ["GPS Sync", "Perpetual Calendar"],
      color: "Black Dial",
    },
    {
      collection: "Astron",
      model: "SBXC003",
      imageSrc: newImageSrc,
      productName: "Seiko Astron SBXC003",
      price: 3000,
      diameter: 42.9,
      thickness: 12.2,
      movement: "GPS Solar 5X53",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Titanium",
      strapMaterial: "Titanium",
      features: ["Dual Time", "Perpetual Calendar"],
      color: "Blue Dial",
    },
    {
      collection: "Astron",
      model: "SBXC037",
      imageSrc: newImageSrc,
      productName: "Seiko Astron SBXC037",
      price: 2500,
      diameter: 42.9,
      thickness: 12.2,
      movement: "GPS Solar 5X53",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Titanium",
      strapMaterial: "Silicone",
      features: ["GPS Sync", "Perpetual Calendar"],
      color: "Gray Dial",
    },
    {
      collection: "Astron",
      model: "SBXC055",
      imageSrc: newImageSrc,
      productName: "Seiko Astron SBXC055",
      price: 2800,
      diameter: 42.9,
      thickness: 12.2,
      movement: "GPS Solar 5X53",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Titanium",
      strapMaterial: "Leather",
      features: ["Dual Time", "Perpetual Calendar"],
      color: "White Dial",
    },
    {
      collection: "Astron",
      model: "SBXC075",
      imageSrc: newImageSrc,
      productName: "Seiko Astron SBXC075",
      price: 3200,
      diameter: 42.9,
      thickness: 12.2,
      movement: "GPS Solar 5X53",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Titanium",
      strapMaterial: "Titanium",
      features: ["GPS Sync", "Perpetual Calendar"],
      color: "Black Dial",
    },
    // King Seiko
    {
      collection: "King Seiko",
      model: "SJE083",
      imageSrc: newImageSrc,
      productName: "King Seiko SJE083",
      price: 3400,
      diameter: 38.1,
      thickness: 11.4,
      movement: "Automatic 6L35",
      waterResistance: "50m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Limited Edition"],
      color: "Silver Dial",
    },
    {
      collection: "King Seiko",
      model: "SJE087",
      imageSrc: newImageSrc,
      productName: "King Seiko SJE087",
      price: 3500,
      diameter: 38.1,
      thickness: 11.4,
      movement: "Automatic 6L35",
      waterResistance: "50m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Limited Edition"],
      color: "Gold Dial",
    },
    {
      collection: "King Seiko",
      model: "SJE089",
      imageSrc: newImageSrc,
      productName: "King Seiko SJE089",
      price: 3600,
      diameter: 38.1,
      thickness: 11.4,
      movement: "Automatic 6L35",
      waterResistance: "50m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Limited Edition"],
      color: "Black Dial",
    },
    {
      collection: "King Seiko",
      model: "SJE091",
      imageSrc: newImageSrc,
      productName: "King Seiko SJE091",
      price: 3700,
      diameter: 38.1,
      thickness: 11.4,
      movement: "Automatic 6L35",
      waterResistance: "50m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Limited Edition"],
      color: "Blue Dial",
    },
    {
      collection: "King Seiko",
      model: "SJE093",
      imageSrc: newImageSrc,
      productName: "King Seiko SJE093",
      price: 3800,
      diameter: 38.1,
      thickness: 11.4,
      movement: "Automatic 6L35",
      waterResistance: "50m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Leather",
      features: ["Date Display", "Limited Edition"],
      color: "Green Dial",
    },
    // Sports
    {
      collection: "Sports",
      model: "SRPD55",
      imageSrc: newImageSrc,
      productName: "Seiko 5 Sports SRPD55",
      price: 300,
      diameter: 42.5,
      thickness: 13.4,
      movement: "Automatic 4R36",
      waterResistance: "100m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Nylon",
      features: ["Day-Date Display", "LumiBrite"],
      color: "Black Dial",
    },
    {
      collection: "Sports",
      model: "SRPD59",
      imageSrc: newImageSrc,
      productName: "Seiko 5 Sports SRPD59",
      price: 320,
      diameter: 42.5,
      thickness: 13.4,
      movement: "Automatic 4R36",
      waterResistance: "100m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Nylon",
      features: ["Day-Date Display", "LumiBrite"],
      color: "Orange Dial",
    },
    {
      collection: "Sports",
      model: "SRPD63",
      imageSrc: newImageSrc,
      productName: "Seiko 5 Sports SRPD63",
      price: 340,
      diameter: 42.5,
      thickness: 13.4,
      movement: "Automatic 4R36",
      waterResistance: "100m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Nylon",
      features: ["Day-Date Display", "LumiBrite"],
      color: "Green Dial",
    },
    {
      collection: "Sports",
      model: "SRPD65",
      imageSrc: newImageSrc,
      productName: "Seiko 5 Sports SRPD65",
      price: 350,
      diameter: 42.5,
      thickness: 13.4,
      movement: "Automatic 4R36",
      waterResistance: "100m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Nylon",
      features: ["Day-Date Display", "LumiBrite"],
      color: "Gray Dial",
    },
    {
      collection: "Sports",
      model: "SRPD67",
      imageSrc: newImageSrc,
      productName: "Seiko 5 Sports SRPD67",
      price: 360,
      diameter: 42.5,
      thickness: 13.4,
      movement: "Automatic 4R36",
      waterResistance: "100m",
      crystal: "Hardlex",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Nylon",
      features: ["Day-Date Disply", "LumiBrite"],
      color: "Blue Dial",
    },
    // Lukia
    {
      collection: "Lukia",
      model: "SSQW047",
      imageSrc: newImageSrc,
      productName: "Seiko Lukia SSQW047",
      price: 800,
      diameter: 28.5,
      thickness: 8.7,
      movement: "Solar 1B35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Date Display", "Perpetual Calendar"],
      color: "White Dial",
    },
    {
      collection: "Lukia",
      model: "SSVW169",
      imageSrc: newImageSrc,
      productName: "Seiko Lukia SSVW169",
      price: 850,
      diameter: 28.5,
      thickness: 8.7,
      movement: "Solar 1B35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Date Display", "Perpetual Calendar"],
      color: "Pink Dial",
    },
    {
      collection: "Lukia",
      model: "SSVW171",
      imageSrc: newImageSrc,
      productName: "Seiko Lukia SSVW171",
      price: 900,
      diameter: 28.5,
      thickness: 8.7,
      movement: "Solar 1B35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Date Display", "Perpetual Calendar"],
      color: "Blue Dial",
    },
    {
      collection: "Lukia",
      model: "SSVW173",
      imageSrc: newImageSrc,
      productName: "Seiko Lukia SSVW173",
      price: 950,
      diameter: 28.5,
      thickness: 8.7,
      movement: "Solar 1B35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Date Display", "Perpetual Calendar"],
      color: "Green Dial",
    },
    {
      collection: "Lukia",
      model: "SSVW175",
      imageSrc: newImageSrc,
      productName: "Seiko Lukia SSVW175",
      price: 1000,
      diameter: 28.5,
      thickness: 8.7,
      movement: "Solar 1B35",
      waterResistance: "100m",
      crystal: "Sapphire",
      caseMaterial: "Stainless Steel",
      strapMaterial: "Stainless Steel",
      features: ["Date Display", "Perpetual Calendar"],
      color: "Red Dial",
    }
  ];

export { seikoWatches };