import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const markPro = localFont({
  src: [
    {
      path: './fonts/Mark Pro.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Mark Pro Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Mark Pro Heavy.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Mark Pro Bold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-mark-pro',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={markPro.variable}>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}